### ISSUE TITLE
Snowball menu - Uncaught reference

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#31] opened 2015-06-01 19:46 UTC
Once we enter the snowball menu, where all articles are being displayed, there is an illegal reference to snowball which is displayed as a console error.
![error2](https://cloud.githubusercontent.com/assets/6703126/7921754/94b648a8-0875-11e5-86ac-cac97e81455b.png)

**Comment by thomaspark** [comment] 2015-06-01 19:49
Duplicate of #23.

**Closed as completed by thomaspark** 2015-06-01 19:49 UTC
